Implement scheduler with Kahn algorithm
google/temporian pull request #20
Opened 2023-02-12 21:23 UTC by achoum

2023-02-13 17:01 UTC, ianspektor approved these changes
Implementation looks fine 👍🏼 does Kahn's algorithm provide any benefits over the previous DFS impl? Both seem to have same O(V+E) space and time complexity

2023-02-13 17:03 UTC, ianspektor requested changes
Check out failing tests

2023-02-14 15:30 UTC, achoum commented on temporian/core/evaluator.py
> +        ready_ops.remove(op)
That's better.

2023-02-15 15:18 UTC, ianspektor approved these changes

2023-02-15 20:35 UTC, achoum commented
Thanks for the review.

2023-02-15 20:36 UTC, merged