Support Duration List in Lag
google/temporian pull request #55
Opened 2023-03-21 18:33 UTC by diegomarvid

Support duration list in lag operator to handle several lags at once.

Depends on #39

2023-03-22 13:42 UTC, ianspektor requested changes

2023-03-22 13:42 UTC, ianspektor commented on temporian/core/operators/arithmetic.py
> -            raise ValueError("event_1 and event_2 must have same sampling.")
Adding item to tomorrow's agenda to discuss best way to handle this

2023-03-22 13:42 UTC, ianspektor commented on temporian/core/operators/lag.py
>      ).outputs()["event"]
This logic could be significantly simplified if we converted a single duration to a list first thing
```
if isinstance(duration, Duration):
    duration = [duration]

if not isinstance(duration, list):
    raise ...

<logic assuming duration is now a list of durations>
```

2023-03-22 13:42 UTC, ianspektor commented on temporian/core/operators/lag.py
> +) -> Union[Event, List[Event]]:
Would be better to return a single event with one feature per each of the created lags. I think at some point we even talked about operators only being able to output events (probably before you joined us).

2023-03-23 14:55 UTC, ianspektor approved these changes

2023-03-24 07:56 UTC, achoum approved these changes
Looks good.
Left a few comments.

2023-03-24 07:56 UTC, achoum commented on temporian/core/operators/lag.py
>  def leak(event: Event, duration: Duration) -> Event:
Update pytype accordingly

2023-03-24 07:56 UTC, achoum commented on temporian/core/operators/lag.py
> +    """Leak operator.
Can you an an explanation what "leak" means here?
Same for lag

2023-03-24 07:56 UTC, achoum commented on temporian/core/operators/lag.py
>  operator_lib.register_operator(LagOperator)
In "build_op_definition", the duration is defined as a float64. Can you make sure (through all the code) that the build_op_definition matches the implementation (pytype, isintance, etc.). I think, currently, some of the pytype are outdated.

2023-03-24 07:56 UTC, achoum commented on temporian/core/operators/lag.py
> +    if isinstance(duration, (Duration, int)):
(Duration, int) is written multiple times. Can you find a way to have a single definition of the supported types?

2023-03-24 07:56 UTC, achoum commented on temporian/implementation/numpy/operators/tests/lag_test.py
> +            output_event = assign(output_event, lagged_event)
Can you test directly the output of the lag/leak operator (instead of using `assign`)?

2023-03-24 07:56 UTC, achoum commented on temporian/core/operators/lag.py
> +def _base_lag(
Why creating an implementation function here? It seems this is the entirety of the

2023-03-24 07:56 UTC, achoum commented on temporian/core/operators/lag.py
> +def _base_lag(
This function is used both for lag and leak. This is the lag/leak file. Therefore, it is probably okay to call this method: "_implementation".

2023-03-24 07:56 UTC, achoum commented on temporian/core/operators/lag.py
> +    should_leak: bool = False,
s/should_leak/leak or is_leak

2023-03-27 19:56 UTC, merged