Remaining calendar ops
google/temporian pull request #58
Opened 2023-03-22 17:29 UTC by ianspektor

Implemented `calendar_`:
- `year`
- `month`
- `hour`
- `minute`
- `second`

From the list in the design doc we're only missing `week_of_year` and `week_of_month` but I'm not too sure as to how to calculate those, added bullet to tomorrow's meeting notes.

2023-03-22 17:55 UTC, diegomarvid approved these changes
LGTM.

For the **week of the year** you can do something like this:
```python
def week_of_year(timestamp):
    dt = datetime.datetime.utcfromtimestamp(timestamp)
    return dt.isocalendar()[1]
```
`isocalendar()` returns the year, week of the year, and weekday as a tuple.

And for the **week of the month** a friend called GPT-4 suggested this:

```python
import datetime

def week_of_the_month(timestamp):
    dt = datetime.datetime.utcfromtimestamp(timestamp)
    
    # Calculate the first day of the month
    first_day_of_month = dt.replace(day=1)
    
    # Calculate the first weekday of the month
    first_weekday = first_day_of_month.weekday()
    
    # Calculate the week of the month
    week_number = (dt.day + first_weekday - 1) // 7 + 1
    
    return week_number

# Example usage:
dt = datetime.datetime(2023, 1, 13)
timestamp = dt.timestamp()
print(week_of_the_month(timestamp))  # Output: 2
```
The last function is quite manual, there are no specific tools for this. I think it's up to you if you want to add it as a functionality in the library.

2023-03-22 19:09 UTC, diegomarvid requested changes
Just missed that we didn't register the operators in `core_mapping.py.` If we decided to not do that due to a new feature in #43, then we could rebase that PR and add the registration mechanism for that implementation. Same for the older calendar operators already merged.

2023-03-23 08:39 UTC, achoum commented on temporian/implementation/numpy/operators/calendar/hour.py
> +    def _get_value_from_datetime(self, dt: datetime) -> Any:
Is there a benefit to do the conversion to int32 after instead of in the "_get_value_from_datetime" function?

2023-03-24 16:49 UTC, ianspektor commented on temporian/implementation/numpy/operators/tests/calendar_year_test.py
> +                    [pd.to_datetime("1970-01-01 00:00:00", utc=True)],
done!

2023-03-24 16:51 UTC, diegomarvid approved these changes

2023-03-24 17:01 UTC, merged